SELECT 
    INFO.CAR_ID, 
    INFO.CAR_TYPE,
    ROUND(INFO.DAILY_FEE * 30 * (1 - DISCOUNT.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS INFO
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT
    ON INFO.CAR_TYPE = DISCOUNT.CAR_TYPE AND DISCOUNT.DURATION_TYPE = '30일 이상'
WHERE
    INFO.CAR_TYPE IN ('세단', 'SUV')
    AND INFO.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
GROUP BY 
    INFO.CAR_ID
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    INFO.CAR_TYPE ASC, 
    INFO.CAR_ID DESC;