SELECT 
    SUB.CAR_ID, 
    SUB.CAR_TYPE, 
    SUB.FEE
FROM 
    (
        SELECT 
            INFO.CAR_ID, 
            INFO.CAR_TYPE,
            ROUND(INFO.DAILY_FEE * 30 * (1 - DISCOUNT.DISCOUNT_RATE / 100)) AS FEE
        FROM 
            CAR_RENTAL_COMPANY_CAR AS INFO
        JOIN 
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT
            ON INFO.CAR_TYPE = DISCOUNT.CAR_TYPE AND DISCOUNT.DURATION_TYPE = '30일 이상'
        WHERE
            INFO.CAR_TYPE IN ('세단', 'SUV')
            AND INFO.CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
            )
    ) AS SUB
WHERE 
    SUB.FEE >= 500000 AND SUB.FEE < 2000000
ORDER BY 
    SUB.FEE DESC, 
    SUB.CAR_TYPE ASC, 
    SUB.CAR_ID DESC;
